version: '2'
services:
    finalcut-app:
        image: finalcut
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://finalcut-mysql:3306/finalcut?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    finalcut-mysql:
        extends:
            file: mysql.yml
            service: finalcut-mysql
